### PR TITLE
Merge request from feature/milestone-05-ui to develop

### PR DESCRIPTION
**Pull request by temesghentekeste**
Hi :hand:,

Milestone 05 is developed by creating a feature branch named  'feature/milestone-05-ui'.

The different components are styled based on the design specified as part of the project requirements.

Kindly request a pull request before I merge my feature branch to the develop branch.

Regards,

### CODE REVIEW

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @temesghentekeste, great job with the styling of the application so far :fireworks: The only requirement preventing me from approving the project is the .gihub/workflows/linters.yml file. Let us kindly used the Microverse recommended file. Kindly check the comments below:

- Kindly use the recommended linter file. Kindly find it [here](https://github.com/microverseinc/linters-config/blob/master/react-redux/.github/workflows/linters.yml)

Once this is resolved, kindly submit another code review request :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by temesghentekeste** [comment]
Hi :hand:,

I have resolved the issue :smile:, kindly request a new code review.

Best regards,
Temesghen

**Comment by mimipeshy** [comment]
## STATUS: APPROVED 🥳 👯 
Hello team @temesghentekeste 👋🏾 👋🏾 congratulations on making it this far in this milestone 🥇 

#### Highlights
- You have worked on all changes requested by the previous TSE ✔️ 

With that, I approve of this project 😄 

Regards
__Peris Ndanu __
[GitHub ](https://github.com/mimipeshy)| [LinkedIn ](https://www.linkedin.com/in/peris-ndanu/)| [Twitter](https://twitter.com/pygirl254)

**Comment by temesghentekeste** [comment]
Thanks, Peris Ndanu for approving the project.

**Pull request merged**
